"use client";

import { useMemo } from "react";
import { StatsGrid, type Stat } from "@/components/stats-grid";
import { AccountRow } from "@/components/account-row";
import {
  type Account,
  type Report,
  type ReportHistoryEntry,
} from "@/lib/placeholder-data";
import { compactNumber, relativeDate } from "@/lib/format";

const CADENCE_LABEL: Record<Report["cadence"], string> = {
  weekly: "Weekly",
  monthly: "Monthly",
  "one-off": "One-off",
};

export function ReportView({
  report,
  accounts,
  historyEntry,
}: {
  report: Report;
  accounts: Account[];
  historyEntry?: ReportHistoryEntry;
}) {
  const avgHealth = accounts.length
    ? Math.round(
        accounts.reduce((s, a) => s + a.healthScore, 0) / accounts.length,
      )
    : 0;
  const topScore = accounts.reduce(
    (m, a) => (a.healthScore > m ? a.healthScore : m),
    0,
  );
  const movers = useMemo(
    () => accounts.filter((a) => Math.abs(a.trendDelta) >= 8),
    [accounts],
  );
  const top = useMemo(
    () =>
      [...accounts].sort((a, b) => b.healthScore - a.healthScore).slice(0, 4),
    [accounts],
  );
  const reach = accounts.reduce((s, a) => s + a.followers, 0);

  const stats: Stat[] = [
    { label: "Avg health", value: avgHealth.toString() },
    {
      label: "Movers",
      value: movers.length.toString(),
      trend: { kind: "neutral", label: "≥8%" },
    },
    { label: "Top score", value: topScore.toString() },
    { label: "Reach", value: compactNumber(reach) },
  ];

  const sentAt = historyEntry?.sentAt ?? report.lastSentAt;

  return (
    <div className="min-h-screen bg-bg text-ink">
      <div className="mx-auto w-full max-w-[680px] px-4 py-8">
        <header className="mb-6 flex items-center justify-between gap-3 border-b border-line pb-4">
          <div className="min-w-0">
            <div
              className="t-meta text-ink-3"
              style={{ fontSize: 10, letterSpacing: "0.18em" }}
            >
              Alert Network · Report
            </div>
            <h1
              className="mt-1 t-display-3 text-ink"
              style={{ fontFamily: "var(--font-unbounded)" }}
            >
              {report.name}
            </h1>
          </div>
          {historyEntry && (
            <span
              className="inline-flex shrink-0 items-center gap-1.5 rounded-full bg-surface-2 px-2.5 py-1 text-ink-2"
              style={{ fontSize: 11, fontFamily: "var(--font-mono)" }}
            >
              Snapshot
            </span>
          )}
        </header>

        <section className="mb-6">
          <p className="t-body text-ink-2">{report.description}</p>
          <div
            data-numeric
            className="mt-3 flex flex-wrap items-center gap-x-2 gap-y-1 text-ink-3"
            style={{ fontSize: 11, fontFamily: "var(--font-mono)" }}
          >
            <span>{CADENCE_LABEL[report.cadence]}</span>
            <Sep />
            <span>{report.recipients} recipients</span>
            <Sep />
            <span>{accounts.length} accounts</span>
            {sentAt && (
              <>
                <Sep />
                <span>Sent {relativeDate(sentAt)}</span>
              </>
            )}
            {historyEntry && (
              <>
                <Sep />
                <span
                  className={
                    historyEntry.status === "delivered"
                      ? "text-good"
                      : "text-bad"
                  }
                >
                  {historyEntry.status === "delivered"
                    ? "Delivered"
                    : "Failed"}
                </span>
              </>
            )}
          </div>
        </section>

        <section className="mb-7">
          <StatsGrid stats={stats} />
        </section>

        {top.length > 0 && (
          <section className="mb-6">
            <h2 className="t-h1 mb-2 text-ink">Top performers</h2>
            <ul className="flex flex-col gap-2">
              {top.map((a) => (
                <li key={a.id}>
                  <AccountRow account={a} />
                </li>
              ))}
            </ul>
          </section>
        )}

        {movers.length > 0 && (
          <section className="mb-6">
            <h2 className="t-h1 mb-2 text-ink">Notable movers</h2>
            <ul className="flex flex-col gap-2">
              {movers.map((a) => (
                <li key={a.id}>
                  <AccountRow account={a} />
                </li>
              ))}
            </ul>
          </section>
        )}

        <footer className="mt-10 border-t border-line pt-4 t-meta text-ink-3" style={{ fontSize: 10 }}>
          Generated by Alert Network · {new Date().toLocaleDateString("en-GB")}
        </footer>
      </div>
    </div>
  );
}

function Sep() {
  return (
    <span aria-hidden className="text-ink-4">
      ·
    </span>
  );
}
